import sys

replacements = {
    'Overview of marketing performance and tasks.': 'Ringkasan performa pemasaran dan daftar tugas.',
    '94.2% On Time': '94.2% Tepat Waktu',
    'Content Published': 'Konten Dipublikasi',
    'across IG/TikTok': 'di IG/TikTok',
    'Avg Engagement': 'Rata-rata Interaksi',
    'Ad Spend (Meta)': 'Pengeluaran Iklan',
    'Pending Approvals': 'Menunggu Persetujuan',
    'Approval Queue': 'Antrean Persetujuan',
    'Content waiting for human review.': 'Konten yang menunggu peninjauan manusia.',
    '<th>Content Title</th>': '<th>Judul Konten</th>',
    '<th>Platform</th>': '<th>Platform</th>',
    '<th>Type</th>': '<th>Jenis</th>',
    '<th>Status</th>': '<th>Status</th>',
    '<th>Action</th>': '<th>Aksi</th>',
    'Draft: Q4 Campaign': 'Draf: Kampanye Q4',
    'Video: Product Demo': 'Video: Demo Produk',
    'WAITING': 'MENUNGGU',
    'REVIEWED': 'DITINJAU',
    'Review': 'Tinjau',
    'Approve': 'Setujui',
    'Quick Actions': 'Aksi Cepat',
    'Create New Campaign': 'Buat Kampanye Baru',
    'Generate AI Caption': 'Buat Teks AI',
    'View Analytics': 'Lihat Analitik',
    'Generate and preview text, visuals, and video scripts before adding them to the pipeline.': 'Buat dan pratinjau teks, visual, dan skrip video sebelum dimasukkan ke dalam alur kerja.',
    'Generate New Assets': 'Buat Aset Baru',
    '<label class="form-label">Content Type</label>': '<label class="form-label">Jenis Konten</label>',
    'Social Media Carousel (5-10 slides)': 'Carousel Media Sosial (5-10 slide)',
    'Short Video Script (TikTok/Reels)': 'Skrip Video Pendek (TikTok/Reels)',
    'Blog Article (SEO Optimized)': 'Artikel Blog (Optimasi SEO)',
    'Single Image + Caption': 'Gambar Tunggal + Teks',
    'Topic / Prompt': 'Topik / Prompt',
    'Generate via Engine': 'Buat via Engine',
    'Trending Topics (Scraped)': 'Topik Tren (Scraped)',
    'AI Agents in Enterprise': 'Agen AI di Perusahaan',
    'High traction on HackerNews. Content Gap: 90%.': 'Sedang ramai di HackerNews. Celah Konten: 90%.',
    'Use Idea': 'Gunakan Ide',
    'Laravel 11 New Features': 'Fitur Baru Laravel 11',
    'Trending on Twitter Tech Community.': 'Trending di Komunitas Teknologi Twitter.',
    'Generated Output Preview': 'Pratinjau Hasil',
    'Review and edit the AI-generated visual/text assets before human approval.': 'Tinjau dan edit aset visual/teks buatan AI sebelum disetujui.',
    'Send to Kanban': 'Kirim ke Kanban',
    'READY TO REVIEW': 'SIAP DITINJAU',
    'Why Next.js is the Future of React.': 'Kenapa Next.js adalah Masa Depan React.',
    'Built-in SSR': 'SSR Bawaan',
    'Server-Side Rendering out of the box for better SEO and speed.': 'Server-Side Rendering otomatis untuk performa dan SEO yang lebih baik.',
    'File-based Routing': 'Routing Berbasis File',
    'No more react-router-dom configuration needed.': 'Tidak perlu konfigurasi react-router-dom lagi.',
    'Add Slide': 'Tambah Slide',
    'AI Generated Caption:': 'Teks Buatan AI:',
    'Copy': 'Salin',
    'Drag and drop workflow management.': 'Manajemen alur kerja seret dan lepas (drag & drop).',
    'Q4 Promo Strategy': 'Strategi Promo Q4',
    'Drafting initial copy...': 'Menyusun draf awal...',
    'React Tutorial Video': 'Video Tutorial React',
    'Script generated. Awaiting human check.': 'Skrip selesai dibuat. Menunggu pengecekan.',
    'Design Request: Banners': 'Permintaan Desain: Banner',
    'Schedule and manage AI-generated content distribution.': 'Jadwalkan dan kelola distribusi konten hasil AI.',
    'AI Optimal Time': 'Waktu Optimal AI',
    'System suggests posting at 18:30 tonight for peak engagement.': 'Sistem menyarankan posting jam 18:30 malam ini untuk interaksi puncak.',
    'Apply Suggestion': 'Terapkan Saran',
    'Schedule Queue': 'Antrean Jadwal',
    'Manage platform connections, monitor publishing logs, and configure A/B testing.': 'Kelola koneksi platform, pantau log, dan atur A/B testing.',
    'Platform Manager (Integrations)': 'Manajer Platform (Integrasi)',
    'CONNECTED': 'TERHUBUNG',
    'NOT CONNECTED': 'TIDAK TERHUBUNG',
    'Connect Webhook': 'Hubungkan Webhook',
    'Publishing Logs': 'Log Publikasi',
    'Auto-publish history and error tracking': 'Riwayat publikasi otomatis dan pelacakan error',
    'Refresh': 'Segarkan',
    '<th>Time</th>': '<th>Waktu</th>',
    'Success': 'Sukses',
    'API Error': 'Error API',
    'Retry': 'Ulangi',
    'Active experiments': 'Eksperimen aktif',
    'RUNNING': 'BERJALAN',
    'Testing Caption: Casual vs Formal': 'Menguji Teks: Santai vs Formal',
    'Create New Test': 'Buat Tes Baru',
    'Deep dive into content performance and AI-generated insights.': 'Analisis mendalam performa konten dan wawasan AI.',
    'Export Custom Report': 'Ekspor Laporan',
    'Performance Tracker': 'Pelacak Performa',
    'Engagement & Reach across all connected platforms': 'Interaksi & Jangkauan di semua platform.',
    'Last 30 Days': '30 Hari Terakhir',
    'This Month': 'Bulan Ini',
    'Last Quarter': 'Kuartal Lalu',
    'AI Learning Insights': 'Wawasan Pembelajaran AI',
    'Format Preference': 'Preferensi Format',
    'Carousel posts with 8 slides perform': 'Postingan Carousel 8 slide memiliki performa',
    'better</strong> than single images on Instagram.': 'lebih baik</strong> daripada gambar tunggal.',
    'Timing Sweet Spot': 'Waktu Terbaik',
    'Posting on Tuesdays at 18:00 yields the highest average engagement rate (6.2%).': 'Posting hari Selasa jam 18:00 menghasilkan rata-rata interaksi tertinggi (6.2%).',
    'Trending Content Topic': 'Topik Tren Konten',
    'Tutorials regarding "Docker" and "Next.js" have the highest save/share ratio this month.': 'Tutorial tentang Docker dan Next.js memiliki rasio simpan/bagikan tertinggi bulan ini.',
    'Custom Reports (Automated)': 'Laporan Kustom (Otomatis)',
    'Configure automated report delivery to stakeholders.': 'Atur pengiriman laporan otomatis ke tim.',
    'Weekly Executive Summary': 'Ringkasan Eksekutif Mingguan',
    '>ACTIVE<': '>AKTIF<',
    'Delivered every Monday at 08:00 AM via Email.': 'Dikirim setiap Senin jam 08:00 pagi via Email.',
    'Monthly Deep Dive': 'Laporan Bulanan Mendalam',
    '>PAUSED<': '>DIJEDA<',
    'Comprehensive metric breakdown. (Not currently scheduled).': 'Rincian metrik komprehensif. (Belum dijadwalkan).',
    'Configure AI behavior, brand identity, and automation workflows.': 'Atur perilaku AI, identitas brand, dan alur kerja otomatis.',
    'Save Changes': 'Simpan Perubahan',
    'Brand & Tone Customizer': 'Kustomisasi Brand & Nada Suara',
    'Default AI Voice Tone': 'Nada Suara AI Bawaan',
    'Professional & Informative': 'Profesional & Informatif',
    'Casual & Friendly': 'Santai & Ramah',
    'Humorous & Witty': 'Humoris & Cerdas',
    'Strictly Academic': 'Sangat Akademis',
    'This tone will be used for all auto-generated content.': 'Nada ini akan digunakan untuk semua konten otomatis.',
    'Multi-Language Output': 'Bahasa Output',
    'Indonesian (ID)': 'Indonesia (ID)',
    'English (US)': 'Inggris (US)',
    'Bilingual (ID/EN Mix)': 'Dwi-bahasa (ID/EN)',
    'Must-Include Keywords': 'Kata Kunci Wajib',
    'Automation Rules (Cron)': 'Aturan Otomatisasi (Cron)',
    'Auto-Approve Content': 'Setujui Konten Otomatis',
    'Publish generated content directly without manual review.': 'Publikasikan konten hasil AI secara langsung tanpa ditinjau manual.',
    'Daily Trend Scraper': 'Pencari Tren Harian',
    'Run scraper at 02:00 AM daily to find new topic ideas.': 'Jalankan pencari tren jam 02:00 pagi setiap hari.',
    'A/B Testing Mode': 'Mode A/B Testing',
    'Automatically generate 2 variations for every caption.': 'Buat 2 variasi otomatis untuk setiap caption.'
}

with open(r"d:\laragon\www\marketing_prototype\index.html", "r", encoding="utf-8") as f:
    content = f.read()

for k, v in replacements.items():
    content = content.replace(k, v)

with open(r"d:\laragon\www\marketing_prototype\index.html", "w", encoding="utf-8") as f:
    f.write(content)

print("Translation completed successfully!")
